version: "3.6"

services:
  fcrepo:
    image: fcrepo/fcrepo:latest
    ports:
      - "8080:8080"
      - "61616:61616"
    environment:
      CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:8080"

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - fcrepo

  fuseki:
    image: atomgraph/fuseki
    ports: 
      - "3030:3030"
    command:
      - --mem 
      - /fcrepo
      
  camel-toolbox:
    build: .
    image: fcrepo/fcrepo-camel-toolbox
    volumes:
      - ./fcrepo-camel-config:/config
    ports:
      - "9080:9080"
