version: "3.6"

services:
  fcrepo:
    image: fcrepo/fcrepo:latest
    ports:
      - "8080:8080"
      - "8181:8181"
      - "61616:61616"

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - collection1

  fuseki:
    image: atomgraph/fuseki
    ports: 
      - "3030:3030"
    command:
      - --mem 
      - /test
      
