version: "3.6"

services:
  fcrepo:
    image: fcrepo/fcrepo:latest
    ports:
      - "8080:8080"
      - "61616:61616"
    environment:
      CATALINA_OPTS: "-Dfcrepo.jms.baseUrl=http://fcrepo:8080"

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - fcrepo

  fuseki:
    image: atomgraph/fuseki
    ports: 
      - "3030:3030"
    command:
      - --mem 
      - /fcrepo
      
  camel-toolbox:
    image: fcrepo/fcrepo-camel-toolbox:latest
    environment:
      FCREPO_BASEURL: "http://fcrepo:8080/fcrepo/rest"
      FCREPO_AUTHHOST: "fcrepo"
      # workaround till Fedora LDPath Service uses FCREPO_AUTHHOST as well:
      FCREPO_AUTHHOSTNAME: "fcrepo"
      FCREPO_AUTHUSERNAME: "fedoraAdmin"
      FCREPO_AUTHPASSWORD: "fedoraAdmin"
      JMS_BROKERURL: "tcp://fcrepo:61616"
      TRIPLESTORE_INDEXER_ENABLED: "true"
      TRIPLESTORE_BASEURL: "http://fuseki:3030/fcrepo"
      SOLR_INDEXER_ENABLED: "true"
      SOLR_BASEURL: "http://solr:8983/solr/fcrepo"
