<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>fcrepo-camel-toolbox</artifactId>
    <groupId>org.fcrepo.camel</groupId>
    <version>7.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>fcrepo-fixity</artifactId>
  <packaging>jar</packaging>

  <name>Fedora Fixity Service</name>
  <description>Camel-based fixity checking service</description>

  <properties>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-core</artifactId>
    </dependency>

    <dependency>
      <groupId>org.fcrepo.camel</groupId>
      <artifactId>fcrepo-camel</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-spring</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>

    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>fcrepo-camel-common</artifactId>
      <version>${project.parent.version}</version>
    </dependency>

    <!-- logging -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-activemq</artifactId>
    </dependency>
    <dependency>
      <groupId>org.messaginghub</groupId>
      <artifactId>pooled-jms</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-http</artifactId>
    </dependency>

    <!-- Testing & Camel Plugin -->
    <dependency>
      <groupId>xerces</groupId>
      <artifactId>xercesImpl</artifactId>
    </dependency>

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>

    <dependency>
      <groupId>org.fcrepo.client</groupId>
      <artifactId>fcrepo-java-client</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-test-spring-junit6</artifactId>
    </dependency>

    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>fcrepo-service-activemq</artifactId>
      <version>${project.parent.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>fcrepo-service-camel</artifactId>
      <version>${project.parent.version}</version>
      <scope>test</scope>
    </dependency>


  </dependencies>

  <build>
    <defaultGoal>install</defaultGoal>

    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>

      <!-- reserve network ports for integration testing -->
      <!-- add configuration file to artifact set for OSGi deployment -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <configuration>
          <portNames>
            <portName>fcrepo.dynamic.test.port</portName>
            <portName>fcrepo.dynamic.jms.port</portName>
            <portName>fcrepo.dynamic.stomp.port</portName>
            <portName>jetty.dynamic.stop.port</portName>
          </portNames>
        </configuration>
      </plugin>

      <!-- integration testing -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <argLine>${jacoco.agent.it.arg}</argLine>
          <systemPropertyVariables>
            <fcrepo.dynamic.jms.port>${fcrepo.dynamic.jms.port}</fcrepo.dynamic.jms.port>
            <fcrepo.dynamic.stomp.port>${fcrepo.dynamic.stomp.port}</fcrepo.dynamic.stomp.port>
            <fcrepo.dynamic.test.port>${fcrepo.dynamic.test.port}</fcrepo.dynamic.test.port>
            <jetty.dynamic.test.port>${jetty.dynamic.test.port}</jetty.dynamic.test.port>
          </systemPropertyVariables>
        </configuration>
      </plugin>

      <!-- Launch jetty for integration testing with Fedora -->
      <plugin>
        <groupId>org.eclipse.jetty.ee10</groupId>
        <artifactId>jetty-ee10-maven-plugin</artifactId>
        <configuration>
          <systemProperties>
            <fcrepo.home>${project.build.directory}/fcrepo-data</fcrepo.home>
            <fcrepo.dynamic.jms.port>${fcrepo.dynamic.jms.port}</fcrepo.dynamic.jms.port>
            <fcrepo.dynamic.stomp.port>${fcrepo.dynamic.stomp.port}</fcrepo.dynamic.stomp.port>
          </systemProperties>
        </configuration>
      </plugin>

      <!--Bring in fcrepo webapp for integration testing-->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>${dependency.plugin.version}</version>
        <executions>
          <execution>
            <id>copy</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.fcrepo</groupId>
                  <artifactId>fcrepo-webapp</artifactId>
                  <version>${fcrepo.version}</version>
                  <type>war</type>
                  <outputDirectory>${project.build.directory}</outputDirectory>
                  <destFileName>fcrepo.war</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
